<?php

declare(strict_types=1);

namespace Yivoff\NifCheck;

class ProvinceEnum
{
    public const PROVINCES
        = [
            'p00' => 'No residente',
            'p01' => 'Álava',
            'p02' => 'Albacete',
            'p03' => 'Alicante',
            'p53' => 'Alicante',
            'p54' => 'Alicante',
            'p04' => 'Almería',
            'p05' => 'Ávila',
            'p06' => 'Badajoz',
            'p07' => 'Islas Baleares',
            'p57' => 'Islas Baleares',
            'p08' => 'Barcelona',
            'p58' => 'Barcelona',
            'p59' => 'Barcelona',
            'p60' => 'Barcelona',
            'p61' => 'Barcelona',
            'p62' => 'Barcelona',
            'p63' => 'Barcelona',
            'p64' => 'Barcelona',
            'p65' => 'Barcelona',
            'p66' => 'Barcelona',
            'p68' => 'Barcelona',
            'p09' => 'Burgos',
            'p10' => 'Cáceres',
            'p11' => 'Cádiz',
            'p72' => 'Cádiz',
            'p12' => 'Castellón',
            'p13' => 'Ciudad Real',
            'p14' => 'Córdoba',
            'p56' => 'Córdoba',
            'p15' => 'A Coruña',
            'p70' => 'A Coruña',
            'p16' => 'Cuenca',
            'p17' => 'Girona',
            'p55' => 'Girona',
            'p67' => 'Girona',
            'p18' => 'Granada',
            'p19' => 'Guadalajara',
            'p20' => 'Guipúzcoa',
            'p71' => 'Guipúzcoa',
            'p21' => 'Huelva',
            'p22' => 'Huesca',
            'p23' => 'Jaén',
            'p24' => 'León',
            'p25' => 'Lleida',
            'p26' => 'La Rioja',
            'p27' => 'Lugo',
            'p28' => 'Madrid',
            'p78' => 'Madrid',
            'p79' => 'Madrid',
            'p80' => 'Madrid',
            'p81' => 'Madrid',
            'p82' => 'Madrid',
            'p83' => 'Madrid',
            'p84' => 'Madrid',
            'p29' => 'Málaga',
            'p92' => 'Málaga',
            'p93' => 'Málaga',
            'p30' => 'Murcia',
            'p73' => 'Murcia',
            'p31' => 'Navarra',
            'p32' => 'Ourense',
            'p33' => 'Oviedo',
            'p74' => 'Oviedo',
            'p34' => 'Palencia',
            'p35' => 'Las Palmas',
            'p76' => 'Las Palmas',
            'p36' => 'Pontevedra',
            'p94' => 'Pontevedra',
            'p37' => 'Salamanca',
            'p38' => 'Santa Cruz de Tenerife',
            'p75' => 'Santa Cruz de Tenerife',
            'p39' => 'Cantabria',
            'p40' => 'Segovia',
            'p41' => 'Sevilla',
            'p91' => 'Sevilla',
            'p42' => 'Soria',
            'p43' => 'Tarragona',
            'p77' => 'Tarragona',
            'p44' => 'Teruel',
            'p45' => 'Toledo',
            'p46' => 'Valencia',
            'p96' => 'Valencia',
            'p97' => 'Valencia',
            'p98' => 'Valencia',
            'p47' => 'Valladolid',
            'p48' => 'Vizcaya',
            'p95' => 'Vizcaya',
            'p49' => 'Zamora',
            'p50' => 'Zaragoza',
            'p99' => 'Zaragoza',
            'p51' => 'Ceuta',
            'p52' => 'Melilla',
        ];
}
